USER_POOL_ID = ''
CLIENT_ID = ''
AWS_REGION = ''
CLIENT_SECRET = ''
PASSWORD_RESET_REQUIRED = 'PASSWORD_RESET_REQUIRED'
DRIVER = 'redshift+redshift_connector'
HOST = ''
RS_PORT = '5439'
DATABASE = ''
USERNAME = ''
PWD = ''

AWS_ACCESS_KEY_ID = ""
AWS_SECRET_ACCESS_KEY = ""
AWS_PROFILE_NAME = ''

HOST_PG = ''
PG_PORT = '5432'
DATABASE_PG = 'rmit_chatgpt_db'
USERNAME_PG = 'postgres'
DRIVER_PG = 'postgresql'
